const PAUSE = 'PAUSA';
const ATTENDANCE = 'ATENDIMENTO';
const BLOCK = 'BLOQUEIO';
const CALL_AGENT = 'CHAMAAGENTE';
const CALL_END = 'FIMCHAMADA';
const ATTENDANCE_END = 'FIMATENDIMENTO';
const FINISHING = 'FINALIZACAO';
const LOGOUT = 'LOGOUT';
const UNPAUSE = 'PAUSACANCELADA';

module.exports = {
    PAUSE,
    ATTENDANCE,
    BLOCK,
    CALL_AGENT,CALL_END,
    ATTENDANCE_END,
    FINISHING,
    LOGOUT,
    UNPAUSE
};
